[package]
name = "statest"
version = "0.2.2"
authors = ["doraneko94 <shuntaro94@gmail.com>"]
edition = "2018"

description   = "Rust crate for statistical test."
documentation = "https://docs.rs/statest/"
repository    = "https://github.com/doraneko94/statest"
keywords      = ["statistics", "statistical_test", "science"]
license       = "MIT"
readme        = "README.md"
categories    = ["algorithms", "science"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
statrs = "0.16.0"
num-traits = "0.2.12"
ndarray = "0.15.6"

[dev-dependencies]
rand = "0.8.5"
rand_distr = "0.4.3"